name: Build

on: workflow_dispatch

jobs:
  Build:
    name: Build/Sign APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.2
          
      - name: Build APK
        id: build
        run: bash ./gradlew :app:assembleFullRelease

      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/full/release
          signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
          keyPassword: ${{ secrets.KEYPASSWORD }}

      - name: Make artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-full-release
          path: ${{steps.sign_apk.outputs.signedReleaseFile}}
